# ========================
# Application
# ========================
spring.application.name=TransitOps_backend

# ========================
# PostgreSQL DataSource
# ========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/transitops}
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA / Hibernate
# ========================
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ========================
# Server
# ========================
server.port=8080

# Default Spring Security User
spring.security.user.name=admin
spring.security.user.password=admin123
